In [46]:
import pandas as pd
import openpyxl

pd.set_option('display.max_rows', 100)

In [ ]:
# Import data
df_first = pd.read_excel('./Names2020_FirstNames_RaceHispanic.xlsx', skiprows=2)
df_first = df_first[:-1]

df_last = pd.read_excel('./Names2020_LastNames_RaceHispanic.xlsx', skiprows=2)
df_last = df_last[:-1]

In [ ]:
# Sort by first name popularity
df_asian_first = df_first.sort_values(by=df_first.columns[8], ascending=False)
df_hispanic_first = df_first.sort_values(by=df_first.columns[-1], ascending=False)
df_native_first = df_first.sort_values(by=df_first.columns[7], ascending=False)

In [ ]:
# Sort by last name popularity
df_asian_last = df_last.sort_values(by=df_last.columns[8], ascending=False)
df_hispanic_last = df_last.sort_values(by=df_last.columns[-1], ascending=False)
df_native_last = df_last.sort_values(by=df_last.columns[7], ascending=False)

### ASIAN

In [42]:
df_asian_first[['FIRST NAME']].head(60)

       FIRST NAME
1            JOHN
0         MICHAEL
3           DAVID
23          KEVIN
13       JENNIFER
8          DANIEL
2           JAMES
21         ANDREW
7           MARIA
31          JASON
9          JOSEPH
33           RYAN
41       MICHELLE
159         GRACE
5         WILLIAM
12    CHRISTOPHER
40           ERIC
46       JONATHAN
98          PETER
43          EMILY
54         JUSTIN
10        RICHARD
872      MOHAMMAD
14        MATTHEW
34          SARAH
24          BRIAN
22        ANTHONY
27        JESSICA
17      ELIZABETH
115         ETHAN
64            AMY
29         JOSHUA
1171     MUHAMMAD
4          ROBERT
30           PAUL
6            MARY
81           ANNA
223           KIM
11         THOMAS
26         STEVEN
91      CHRISTINE
19          LINDA
25          SUSAN
502         JENNY
126          ALEX
929      MOHAMMED
73      ALEXANDER
1474        THANH
68       BENJAMIN
35           LISA
153        SOPHIA
61        BRANDON
140         HENRY
20           MARK
92         NATHAN
39          NANCY
1548         HONG
69         ANGELA
189         HELEN
1583       PHUONG

In [36]:
df_asian_last[['LAST NAME']].head(20)

    LAST NAME
28     NGUYEN
18        LEE
62      PATEL
70        KIM
92       CHEN
100      TRAN
150      WANG
153        LI
155     SINGH
198      YANG
199        LE
231       LIU
251     ZHANG
258       LIN
304      PHAM
270      WONG
313     HUANG
317        WU
302      KHAN
273      PARK

### HISPANIC

In [47]:
df_hispanic_first[['FIRST NAME']].head(80)

      FIRST NAME
7          MARIA
15          JOSE
59          JUAN
90          LUIS
94        CARLOS
8         DANIEL
3          DAVID
149        JESUS
160          ANA
172       MIGUEL
185        JORGE
0        MICHAEL
142        ANGEL
22       ANTHONY
225    FRANCISCO
147       VICTOR
212         ROSA
232       MANUEL
17     ELIZABETH
27       JESSICA
1           JOHN
12   CHRISTOPHER
179      ANTONIO
262        OSCAR
308    ALEJANDRO
4         ROBERT
46      JONATHAN
238       CARMEN
143      GABRIEL
9         JOSEPH
292      RICARDO
260        MARIO
316        PEDRO
329       HECTOR
13      JENNIFER
110    CHRISTIAN
323      ROBERTO
350       JAVIER
132       MARTHA
231       ADRIAN
38        SANDRA
73     ALEXANDER
130        DIANA
364      EDUARDO
368     FERNANDO
372       RAFAEL
29        JOSHUA
23         KEVIN
52         LAURA
242     VERONICA
14       MATTHEW
148       GLORIA
163     ISABELLA
99      VICTORIA
44        ASHLEY
440    GUADALUPE
106       ANDREA
18      PATRICIA
10       RICHARD
429         RAUL
424       SERGIO
21        ANDREW
433        DIEGO
36         JACOB
56     STEPHANIE
454        JULIO
236      VANESSA
293      CLAUDIA
126         ALEX
43         EMILY
5        WILLIAM
464        CESAR
285       JULIAN
445        RUBEN
196       MARTIN
53       MELISSA
202       MONICA
138       ALEXIS
489       ANDRES
72        SAMUEL

In [38]:
df_hispanic_last[['LAST NAME']].head(20)

    LAST NAME
5      GARCIA
7   RODRIGUEZ
9    MARTINEZ
10  HERNANDEZ
11      LOPEZ
12   GONZALEZ
20      PEREZ
24    SANCHEZ
26    RAMIREZ
37     TORRES
38     FLORES
45     RIVERA
48      GOMEZ
51       DIAZ
54       CRUZ
55      REYES
61    MORALES
67      ORTIZ
69  GUTIERREZ
73      RAMOS

### NATIVE

In [48]:
df_native_first[['FIRST NAME']].head(80)

      FIRST NAME
0        MICHAEL
2          JAMES
1           JOHN
4         ROBERT
3          DAVID
5        WILLIAM
6           MARY
9         JOSEPH
10       RICHARD
12   CHRISTOPHER
8         DANIEL
16       CHARLES
22       ANTHONY
11        THOMAS
29        JOSHUA
13      JENNIFER
31         JASON
14       MATTHEW
19         LINDA
61       BRANDON
18      PATRICIA
36         JACOB
27       JESSICA
26        STEVEN
54        JUSTIN
35          LISA
17     ELIZABETH
23         KEVIN
42       KENNETH
24         BRIAN
41      MICHELLE
20          MARK
33          RYAN
21        ANDREW
51        RONALD
44        ASHLEY
37       TIMOTHY
30          PAUL
57          GARY
49        AMANDA
53       MELISSA
34         SARAH
47        DONALD
88         AARON
78         TYLER
82         LARRY
50      KIMBERLY
28       BARBARA
40          ERIC
32         KAREN
38        SANDRA
69        ANGELA
63        GEORGE
100       JORDAN
56     STEPHANIE
62         DONNA
79        BRENDA
71        SHARON
60       REBECCA
46      JONATHAN
134      RAYMOND
104         KYLE
66        EDWARD
80      SAMANTHA
127       JEREMY
131        JERRY
72        SAMUEL
158        AMBER
124        TERRY
74       PATRICK
92        NATHAN
70       CYNTHIA
67         CAROL
221         CODY
48      NICHOLAS
25         SUSAN
118       TAYLOR
93       HEATHER
174        JESSE
195      CRYSTAL

In [49]:
df_native_last[['LAST NAME']].head(80)

       LAST NAME
0          SMITH
1        JOHNSON
2318       BEGAY
2572      YAZZIE
4          JONES
2       WILLIAMS
3          BROWN
2002    LOCKLEAR
8          DAVIS
13        WILSON
15        THOMAS
22      THOMPSON
6         MILLER
19       JACKSON
23         WHITE
18           LEE
21        MARTIN
29         LEWIS
9       MARTINEZ
85         JAMES
172         HUNT
5         GARCIA
16        TAYLOR
14      ANDERSON
27         CLARK
6486     BENALLY
39         SCOTT
17         MOORE
6739      TSOSIE
35          KING
43        NELSON
31        WALKER
7160         NEZ
265       JACOBS
5122    OXENDINE
25        HARRIS
40          HILL
34         ALLEN
918         JOHN
46      MITCHELL
11         LOPEZ
33         YOUNG
44         BAKER
52      PHILLIPS
68        MORGAN
42         ADAMS
152        HENRY
50       ROBERTS
3445         JOE
36        WRIGHT
2536      CHAVIS
32          HALL
99          LONG
63        MORRIS
229       GEORGE
57        PARKER
49        CARTER
30      ROBINSON
65          COOK
74          REED
41         GREEN
24       SANCHEZ
82    RICHARDSON
83        CHAVEZ
10     HERNANDEZ
75          BELL
53         EVANS
47      CAMPBELL
8976         JIM
6928        CHEE
58       EDWARDS
7      RODRIGUEZ
8480     CHARLEY
145     HARRISON
59       COLLINS
66        ROGERS
243     SANDOVAL
60       STEWART
140      STEVENS
78          WARD